# Generated by Django 4.1.7 on 2023-06-18 16:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='帖子标题')),
                ('content', ckeditor.fields.RichTextField()),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('thumb_up', models.PositiveIntegerField(default=0, verbose_name='点赞量')),
                ('thumb_down', models.PositiveIntegerField(default=0, verbose_name='点踩数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
    ]
