# Generated by Django 4.1.7 on 2023-06-08 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='宠物名称')),
                ('sex', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('neutered', models.SmallIntegerField(choices=[(0, '已绝育'), (1, '未绝育')], default=0, verbose_name='是否绝育')),
                ('address', models.CharField(max_length=255, verbose_name='领养地址')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('brief_intro', models.TextField(verbose_name='宠物简介')),
                ('avatar', models.FileField(upload_to=pet.models.pet_avatar_path, verbose_name='头像')),
                ('adopt_status', models.SmallIntegerField(default=0, verbose_name='领养状态')),
            ],
            options={
                'verbose_name': '宠物管理',
                'verbose_name_plural': '宠物管理',
            },
        ),
        migrations.CreateModel(
            name='PetGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('picture', models.FileField(upload_to=pet.models.goods_picture_path, verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('unit', models.CharField(max_length=20, verbose_name='商品计量单位')),
                ('stock', models.IntegerField(verbose_name='商品库存')),
                ('brief_intro', models.TextField(verbose_name='尚品简介')),
            ],
            options={
                'verbose_name': '商品管理',
                'verbose_name_plural': '商品管理',
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=pet.models.pet_image_path, verbose_name='宠物照片')),
                ('photograph_time', models.DateField(verbose_name='拍摄时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_image_pet', to='pet.pet', verbose_name='宠物')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_image_photographer', to=settings.AUTH_USER_MODEL, verbose_name='拍摄者')),
            ],
            options={
                'verbose_name': '宠物照片',
                'verbose_name_plural': '宠物照片',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='订单号')),
                ('address', models.CharField(max_length=150, verbose_name='收货地址')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_goods', to='pet.petgoods', verbose_name='订单商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='订单用户')),
            ],
            options={
                'verbose_name': '购物订单',
                'verbose_name_plural': '购物订单',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='收藏时间')),
                ('favorite_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_object', to='pet.petgoods', verbose_name='收藏对象')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏用户')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('apply_status', models.SmallIntegerField(default=2, verbose_name='审核状态')),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt_pet_adopter', to=settings.AUTH_USER_MODEL, verbose_name='领养者')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopt_pet_pet', to='pet.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '领养订单',
                'verbose_name_plural': '领养订单',
            },
        ),
    ]
