# Generated by Django 4.1.7 on 2023-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_status',
            field=models.SmallIntegerField(choices=[(0, '拉黑'), (1, '正常')], default=1, verbose_name='状态'),
        ),
    ]
